title: W21 Wiki
description: ML Ops, GCP, Azure, data science, digital marketing, SRE, and soft skills (decision making, communication)
theme: just-the-docs

url: https://wiki.workinthe21st.com

aux_links:
  Template Repository: https://github.com/smatusiak/wiki
